In [6]:
%matplotlib inline
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

c_class = {"C20/25": 0, "C25/30": 1, "C30/37": 2, "C35/45": 3, "C40/50": 4, "C45/55": 5,
           "C50/60": 6, "C55/67": 7, "C60/75": 8, "C70/85": 9, 
           "C80/95": 10,"C90/105": 11}
c_fck = np.array([20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90])
c_epsc2 = np.array( [2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.2, 2.3, 2.4 , 2.5, 2.6])
c_epscu2 = np.array([3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.1, 2.9, 2.7 , 2.6, 2.6])
c_n = np.array(     [2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 1.75, 1.6, 1.45, 1.4, 1.4])
epsc12 = c_epsc2/c_epscu2

In [7]:
chi_1 = 1.0-epsc12/(c_n+1)
chi_1

array([0.80952381, 0.80952381, 0.80952381, 0.80952381, 0.80952381,
       0.80952381, 0.80952381, 0.74193548, 0.69496021, 0.63718821,
       0.59935897, 0.58333333])

In [8]:
chi_2 = 1.0-((c_n+1)*(c_n+2)*0.5-epsc12**2)/((c_n+1)*(c_n+2)*chi_1)
chi_2

array([0.41596639, 0.41596639, 0.41596639, 0.41596639, 0.41596639,
       0.41596639, 0.41596639, 0.39191211, 0.37723377, 0.36200652,
       0.35481646, 0.35294118])

In [9]:
chi = 0.5*chi_1/chi_2
chi

array([0.97306397, 0.97306397, 0.97306397, 0.97306397, 0.97306397,
       0.97306397, 0.97306397, 0.94655851, 0.92112671, 0.88007836,
       0.84460423, 0.82638889])

In [10]:
ic = c_class["C55/67"]
chi[ic]

0.9465585112728139